### ISSUE TITLE
Module not found: Can't resolve 'fs'

### ISSUE THREAD

**Issue by m-salaudeen** [deltazero-cz/node-xsd-validator#3]
Hello,

I installed this package and attached is an image of the error I get when ever I start up the app:

<img width="1008" alt="Screenshot 2024-02-15 at 13 14 50" src="https://github.com/deltazero-cz/node-xsd-validator/assets/157492979/0c75ae6e-3174-4ffe-a3f5-e3748cfeffdb">

Here is my implementation

`import validateSchema from "xsd-validator";

const handleButtonChange = () => {
console.log(validateSchema("<xml...", "<xs:schema..."));
}`

I don't even have to click the button before it throw error

I am using this in a NextJS app version 14 Typescript

Also I have installed `libxmljs` but still the same issue

**Comment by deltazero-cz** [comment]
What environment are you using? Module `fs` should be a native in node, https://nodejs.org/api/fs.html
