### ISSUE TITLE
xmljs.node: invalid ELF header

### ISSUE THREAD

**Issue by davidmricardo** [deltazero-cz/node-xsd-validator#4]
I build my node-api with pkg both for windows and linux.
I'm working on a windows machine and when I run it in linux it gave me the error:
Lib not found, so I added this in package.json:

"pkg": {
    "scripts": [
                     "../../node_modules/libxmljs/**/*"
]

Now it is giving the error:

xmljs.node: invalid ELF header

Is there any solution for that?

**Comment by deltazero-cz** [comment]
Try `npm rebuild`

**Comment by davidmricardo** [comment]
:( Didn't help. Didn't change anything.

Is there any parameter I should pass to pkg?

**Comment by deltazero-cz** [comment]
I cannot say. I think it's a problem with libxmljs binary. Maybe try installing libxmljs separately before xsd-validator, hope it works.

**Comment by davidmricardo** [comment]
It didn't work either.
I need to find another way.
Thanks
